export const palette = {
  primary: '#006874',
  onPrimary: '#ffffff',
  primaryContainer: '#9EEFFD',
  onPrimaryContainer: '#001F24',
  secondary: '#4A6267',
  secondaryContainer: '#CCE8EE',
  surface: '#FAFDFE',
  surfaceContainer: '#E0F4F6',
  surfaceContainerHigh: '#D0EEF2',
  surfaceVariant: '#DBE4E6',
  onSurface: '#171D1E',
  onSurfaceVariant: '#3F4E51',
  outline: '#6F797A',
  outlineVariant: '#BEC8CA',
  background: '#DDF3F7',
  error: '#B3261E',
  errorContainer: '#F9DEDC',
  success: '#1A6B4F',
  successContainer: '#C8F0DC',
  warning: '#7B4F00',
  warningContainer: '#FFDDB0',
  star: '#F4A020',
} as const;

export const {
  primary, onPrimary, primaryContainer, onPrimaryContainer,
  secondary, secondaryContainer,
  surface, surfaceContainer, surfaceContainerHigh, surfaceVariant,
  onSurface, onSurfaceVariant,
  outline, outlineVariant,
  background,
  error, errorContainer,
  success, successContainer,
  warning, warningContainer,
  star,
} = palette;
